name: Smoke Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * mon-fri"

jobs:
  smoke-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup selenium Grid
        run: docker-compose up -d

      - name: Build with Maven
        run: mvn -B clean test site -Dfile=Smoke.xml --file pom.xml

      - name: Cleanup selenium Grid
        run: docker-compose down